#!/usr/bin/env python3

import requests
import json

class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author

title = input("Enter book title: ")
author = input("Enter author name: ")

book = Book(None, title, author)  # ID is None for new book
book_data = json.dumps(book.__dict__)
headers = {'Content-Type': 'application/json'}

response = requests.post('http://localhost:3000/books', data=book_data, headers=headers)
print(response.json())
