#!/usr/bin/env python3

import requests

class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author

book_id = input("Enter book ID to delete: ")
response = requests.delete(f'http://localhost:3000/books/{book_id}')
print(response.json())
