#!/usr/bin/env python3

import requests

class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author

book_id = input("Enter book ID: ")
response = requests.get(f'http://localhost:3000/books/{book_id}')
book_data = response.json()
book = Book(**book_data)
print(f'ID: {book.id}, Title: {book.title}, Author: {book.author}')
