#!/usr/bin/env python3

import requests

class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author

response = requests.get('http://localhost:3000/books')
books = [Book(**book_data) for book_data in response.json()]
for book in books:
    print(f'ID: {book.id}, Title: {book.title}, Author: {book.author}')
