#!/usr/bin/env python3

import requests
import json

class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author

book_id = input("Enter book ID to update: ")
title = input("Enter new title: ")
author = input("Enter new author: ")

book = Book(book_id, title, author)
book_data = json.dumps(book.__dict__)
headers = {'Content-Type': 'application/json'}

response = requests.put(f'http://localhost:3000/books/{book_id}', data=book_data, headers=headers)
print(response.json())
